### ISSUE TITLE
Cardano Indonesia Meeting #13: 04 April 2022 until 10 April 2022

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-operations#33]
## Cardano Indonesia Meeting: 04 April 2022 until 10 April 2022
- Last Meeting - #32  
- Next Meeting - TBD 

### Attendees
Andreas Sosilo (@andreassosilo)
Andre Cahyadi (@andrecahyadi)
Andy Sibuea (@zicozibu)
Dion Setyotomo (@dionsetyotomo) 
Jordy Vincent (@jordyvincent)

### Apologies
Yan Tirta (@YanTirta)
Xavier Daniswara(@syarbel)
Caliburn (@CryptoCaliburn) 
Dani Ihza Farrosi (@danivideda)

# Reviewing Tasks
- Polling for new team meeting schedule #11 by @danivideda 
- Request new sub-category for Cardano Forum #26 by @andreassosilo 

# Meeting Topics

### Eastern Town Hall Indonesia
- vCA phase in Catalyst Fund 8 (DONE)
- Next Eastern Town Hall Meetup will be IdeaFest Reels -> Saturday, 09 April 2022
- Don't forget to prepare for "IdeaFest Reels" in Eastern Town Hall for the proposers in Fund 8
- Proposal from Indonesia & Eastern Town Hall (see below):

👉 Proposal Fund 8 yang dibuat oleh komunitas Indonesia:
- Leveling Up Cardano Indonesia IG
link: https://cardano.ideascale.com/c/idea/396542
- SPO Delegators Communal CNFT
link: https://cardano.ideascale.com/c/idea/396662
- Cardano Hub Indonesia - Video Series
link: https://cardano.ideascale.com/c/idea/401709
- Loyalty Point for Developers
link https://cardano.ideascale.com/c/idea/405253

👉  [Eastern Town Hall](https://t.me/EHTIndonesia/6575)
1. Eastern Town Hall Team Operation - https://cardano.ideascale.com/c/idea/403802
2. Connecting Asian Voter and Proposer - https://cardano.ideascale.com/c/idea/404182
3. Onboarding East Asia Today - https://cardano.ideascale.com/c/idea/404177
4. Grow East Asia, Grow Cardano - https://cardano.ideascale.com/c/idea/399482
5. Eastern Catalyst School - https://cardano.ideascale.com/c/idea/405311 

### Eastern Catalyst School
- Preparation for Fund 9

### Cardano Hub Indonesia - Workshops
- Next workshop: "Cardano Ecosystem" -> 17 April 2022
- Topic: Discuss about Milkomeda, MilkySwap, Charles x Snoop Dogg, Minswap x COTI (Djed), and other update in Cardano Ecosystem
- Received 2nd batch of fund from catalyst@iohk.io -> Rate at 1.2 USD / ADA
- Flyer for Cardano Ecosystem April 2022 workshop - ?? April 2022 by @YanTirta 
- @andreassosilo : payment for Mora's flyer to @YanTirta -> will be transferred by today
- For 15 May 2022: we will do workshop -> "Wallet & Delegation" + AMA (Ask Me Anything) -> anyone could ask and answer. And try to ask Budi Isman (Blue Korintji) / Shunsuke Murasaki (Emurgo Indonesia) / Suryono (Alko Indonesia - https://alko.id/) to speak in AMA
- @dionsetyotomo : sent invitation to Blue Korintji
- For June/July, already ask Andrew Ponto (SPO Kawanua Pool) to give workshop about how to setup stake pool in Cardano

### DID for Cardano Indonesia Community
- 1st workshop is done
- Doing research with Daniel Bonfill 
- @danivideda will start helping on research and learn about Atala PRISM, SSI, DID and VC

### Community Web Portal in Bahasa
- Update layout
- Test backend
- Final test at 15 April 2022
- Prepare articles + Google Forms : https://forms.gle/AaHU5M9jzTnJh6Zv8
- @andreassosilo needs to submit article about Cardano tech & @YanTirta needs to submit articles about Catalyst (Governance)

### Collaboration
- Collaboration with TRIV
- Review about event with PINTU from @dionsetyotomo -> Link: https://www.youtube.com/watch?v=1bscjHcNVtU
- About TRIV -> contact with @dionsetyotomo @YanTirta 
- Discussion with "Dokter Peduli" -> @andrecahyadi had discussion with Ibu Mimy -> please create presentation about "Cardano Indonesia Community" -> waiting proposal from Cardano Indonesia (@YanTirta & Andrew Ponto)

### Proposal Cardano Indonesia for Catalyst Fund 9
- Title: **"Cardano Indonesia Team Operation"**
- Ask funding for our operational in Cardano Indonesia Hub
- Prepare the proposal from now
- @YanTirta & @dionsetyotomo : create Google Sheets for our draft proposal, try to use Eastern Town Hall Team Operation proposal
- Example proposal from Eastern Town Hall Team Operation: https://docs.google.com/document/d/1lfgePHdJyEW2pDZ8EnL2wCjuJ7wgBQHc/edit?usp=sharing&ouid=116783838297278560675&rtpof=true&sd=true
- The core team must be compensate -> meeting: 15 USD/hour for example
- @dionsetyotomo will create matrix
- Range from admin (30 USD/hour) until developer (100 USD/hour) -> example from other proposal in Catalyst
- Need brainstorming on next meeting
- Put maximum cap for contribution each month

### Cardano Indonesia Treasury Wallet
- We can use both: **$cardano_id** and **$cardano.id** -> for donation (ADA or NFT)

### Team Update
- @jordyvincent : needs to give @YanTirta & @CryptoCaliburn access to the Twitter account (retweet, comment, etc.)
- If anyone else need access to TweetDeck: https://tweetdeck.twitter.com/

**Comment by andrecahyadi** [comment]
Baru tau ada proposal ke-4 dari Indonesia, aktif di grup komunitas Cardano kah mereka?

**Comment by andreassosilo** [comment]
> Baru tau ada proposal ke-4 dari Indonesia, aktif di grup komunitas Cardano kah mereka?

Dari komunitas. Kayanya di Discord bro @andrecahyadi . Mungkin bro @YanTirta ada info lebih.

**Comment by syarbel** [comment]
Proposer nya nongol waktu di grup CA/vCA setelah workshop ECS di Fund 8. Dia baru tahu kalau komunitas kita bisa konsultasi terkait pembuatan proposal juga.

Basically proposalnya mau nerapin “loyalty points” yang udah berjalan di tempat dia kerja, buat developer di Cardano gitu.

Salam,

Xavier Daniswara
📱+62 823-2293-4252
