### ISSUE TITLE
Cardano Indonesia Meeting #16: 16 May 2022 until 22 May 2022

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-operations#37]
## Cardano Indonesia Meeting: 16 May 2022 until 22 May 2022
- Last Meeting - #35    
- Next Meeting - TBD 

### Attendees:
Andreas Sosilo (@andreassosilo)
Andre Cahyadi (@andrecahyadi)
Dani Ihza Farrosi (@danivideda)
Dion Setyotomo (@dionsetyotomo)
Xavier Daniswara (@syarbel)
Yan Tirta (@YanTirta)
Ayu Kusumaningtyas

### Apologies:
Andy Sibuea (@zicozibu)
Jordy Vincent (@jordyvincent)
Caliburn (@CryptoCaliburn) 

## Pending Tasks
- Request a new sub-category for Cardano Forum #26 by @andreassosilo 
- Create Cardano Indonesia community profile #36 by @andrecahyadi @dionsetyotomo 

### 1. Eastern Town Hall Indonesia
- [Meetup registration](https://us02web.zoom.us/meeting/register/tZcqcOCopjsuGNd0IAZPoGfYNEYCXO_prtEd) for Saturday, 21 May 2022 at 16:00-18:00 WIB
- Eastern Catalyst School:
  - Preparation for Fund 9
  - Give 1st workshop: "F9: Introduction to Catalyst" in 🇮🇩 Indonesian language
  - Prepare material for the workshop by @syarbel @zicozibu @danivideda 
  - Flyer for the workshop created by @YanTirta
  - Rewards: 200k IDR in ADA
  - Moderator: Ayu Kusumaningtyas
  - Speaker @danivideda @zicozibu 
  - Hosts: @andreassosilo @YanTirta 

### 2. Social Engagement
- Collected data ["Cardano Indonesia Social Media Growth"](https://docs.google.com/spreadsheets/d/1suCmuWlZm6jgK67lMWZJP77Fqzb4isye-AO_Zgidri8/edit#gid=1014608380) (form created by @dionsetyotomo 
Input by: @andreassosilo 
- **Instagram**
   - Need to ask @jordyvincent -> how do we want to continue with the Instagram?
   - Ayu: increase engagement in Instagram to increase follower. Regular post in specific time.
- **Twitter**
   - Twitter Space: @dionsetyotomo & @CryptoCaliburn: starting regular Twitter Space and/or Telegram Voice during weekdays about Cardano and its ecosystem. This will be started regularly around 17:15 or after 20:00 WIB

### 3. Community Operation
- Plan to have dedicated admins.
- Proposal Draft in F9:
   - Title: **"Cardano Indonesia Hub"**
   - Ask funding for Cardano Indonesia Hub operation
   - @YanTirta & @dionsetyotomo: create Google Sheets for our draft proposal, try to use the Eastern Town Hall Team Operation proposal. [Google Sheet](https://docs.google.com/spreadsheets/d/1yIpVVbFUZHuze5fxZzMfTYQeZRz7auxUX6EMloq8WjY/edit?usp=sharing) 
   - Example proposal from Eastern Town Hall Team Operation: https://docs.google.com/document/d/1lfgePHdJyEW2pDZ8EnL2wCjuJ7wgBQHc/edit?usp=sharing&ouid=116783838297278560675&rtpof=true&sd=true
   - The core team must be compensated -> meeting: 15 USD/hour for example
   - @dionsetyotomo will create a matrix
   - Range from admin (30 USD/hour) until developer (100 USD/hour) -> example from other proposal in Catalyst
   - Need brainstorming on the next meeting
   - Put a maximum cap for the contribution each month
   - Target: support members to become proposers and submit proposals in each Catalyst Fund, collaborate with members from other countries
   - Input from @dionsetyotomo & @YanTirta : for event (max. 3 months), for regular meetup/workshops (max. 6 months)

### 4. Collaboration
- TRIV
   - Randy contacted @YanTirta -> to create a Cardano event in Surabaya -> budget from TRIV (10 million IDR) -> hybrid event around 25 June 2022 -> will be organized by @YanTirta, @dionsetyotomo, & @CryptoCaliburn 
- Rantai Kotak 
   - Invites us for next week AMA -> Saturday, 28 May 2022 -> to boost Eastern Catalyst School KPI and share about Project Catalyst in Cardano blockchain. Speakers -> TBD

### 5. Cardano Summit 2022
- Around August or September 2022
- Community workshop
- What do we want to do for this year -> small gathering in Jakarta?
- Need to ask EMURGO Indonesia if they will create an event for Cardano Summit 2022 by @zicozibu 
- @dionsetyotomo will contact Omar & Doddy
- Other option: to have a self funded event, need some venue space options: co-working spaces, restaurants with min budget around 100k-150k

### 6. Cardano Indonesia Treasury Wallet
- We can use both: **$cardano_id** and **$cardano.id** -> for donation (ADA or NFT)

### 7. Misc Information
- @YanTirta : include Ayu to support @YanTirta. Yan wants to develop other regions in the Eastern Town Hall.

### a. Cardano Hub Indonesia - Workshops
- Preparing to submit monthly KPI report for May 2022 to IOG Catalyst Team by @andreassosilo (deadline 24 May 2022)
- Budget for May 2022 received from IOG-> **Rate: 0.659 USD/ADA**
- Next workshop:  Sunday, 29 May 2022 at 19:00-21:00 WIB
- Topic: "Cardano Ecosystem May 2022"
- Speaker: Darma from KITA Cardano, @CryptoCaliburn & @dionsetyotomo 
- Darma from KITA Cardano will give 15 mins presentation about his company NFT project for music festival in Jakarta
- Reward: 2x 10 ADA + 2x (NFT + 2 ADA) -> already sent to $cardano_id by @andreassosilo , verified by @andrecahyadi 
- Andrew Ponto (SPO Kawanua Pool) could not give a workshop about how to setup stake pool in Cardano in June 2022. Will be rescheduled to August/September 2022
- Next Workshops' preparation:
1. 12 June 2022: Introduction to Cardano NFT (how to mint, how to register/validate in marketplace, royalty CIP-0027, how to get profit from buying/selling NFT, discussion about NFT use case, Omar from Fibo EMURGO, etc.)
2. 26 June 2022: Cardano Ecosystem June 2022
3. 10 July 2022: AMA (with Blue Korintji??) or Introduction to Marlowe -> TBD

### b. DID for Cardano Indonesia Community
- Get information about WAL-CLI -> needs to be read and tested
- @danivideda starts helping on research and learning about Atala PRISM, SSI, DID, and VC
- Submit the monthly KPI report for May 2022 to IOG Catalyst Team

### c. Community Web Portal in Bahasa
- Link website: https://www.adakita.xyz/
- Waiting for article submission
- Compensation -> 10 USD/article becoming 10 ADA/article -> needs to be verified by @dionsetyotomo 
- Invitation Link: https://docs.google.com/forms/d/e/1FAIpQLSd68yh8gLdurHwePjz_c7wxA1JmqU2KGh6eXkqP1obQeYPOTA/viewform?pli=1
- Fund for May 2022 not yet received -> will be confirmed again later
- Do not forget to submit KPI Report May 2022 @dionsetyotomo

**Comment by andrecahyadi** [comment]
@andreassosilo Itu hadiah 2x10 ADA & 2xNFT bukannya buat workshop tgl 15 May lalu bro?

**Comment by andreassosilo** [comment]
Done. Issue closed.
