### ISSUE TITLE
Cardano Indonesia Meeting #18: 30 May 2022 until 05 June 2022 

### ISSUE THREAD

**Issue by andreassosilo** [cardano-indonesia/cardano-indonesia-operations#43]
## Cardano Indonesia Meeting: 30 May 2022 until 05 June 2022 
- Last Meeting - #39     
- Next Meeting - #44  

### Attendees:
Andreas Sosilo (@andreassosilo)
Andre Cahyadi (@andrecahyadi)

### Apologies:
Andy Sibuea (@zicozibu)
Jordy Vincent (@jordyvincent)
Caliburn (@CryptoCaliburn) 
Xavier Daniswara (@syarbel)
Dani Ihza Farrosi (@danivideda)
Dion Setyotomo (@dionsetyotomo)
Yan Tirta (@YanTirta)
Ayu Kusumaningtyas

## Pending Tasks
- Request a new sub-category for Cardano Forum #26 by @andreassosilo 
- Create Cardano Indonesia community profile #36 by @andrecahyadi @dionsetyotomo 

### 1. Eastern Town Hall Indonesia
- Next meetup: Saturday, 04 June 2022 @ 09:00-11:00 UTC
- Eastern Catalyst School:
  - Preparation for 2nd workshop: "**F9: How to submit a proposal - Part 1**"
  - Give 2nd workshop  in 🇮🇩 Indonesian language
  - Prepare material for the workshop by @syarbel -> [Mengajukan Proposal di Catalyst Fund 9](https://docs.google.com/presentation/d/1SQmnsXcUGxIMXDeYoA3bgntIOG0nJzzhkOi-8R3Dki0/edit#slide=id.g1309cb42288_0_1872)
  - Flyer for the workshop created by @YanTirta
  - Rewards: 20 ADA * 5 persons = 100 ADA (need to be discussed, based on the funded proposal)
  - Moderator: Ayu Kusumaningtyas
  - Speakers: @syarbel, @andreassosilo 
- Ayu: increase engagement in ETH Instagram to increase followers. Regular post at a specific time.
  To do: follow up with @YanTirta 

### 2. Social Engagement
- Collected data ["Cardano Indonesia Social Media Growth"](https://docs.google.com/spreadsheets/d/1suCmuWlZm6jgK67lMWZJP77Fqzb4isye-AO_Zgidri8/edit#gid=1014608380) (a form created by @dionsetyotomo 
Input by: @andreassosilo -> updated on 31 May 2022
- **Instagram** -> Status: ***On Hold***
   - Need to ask @jordyvincent -> how do we want to continue with Instagram? Ask for access, so Ayu Kusumaningtyas could work on it
- **Twitter**
   - Ayu, increase engagement in Twitter to increase followers. Regular post at a specific time. @andreassosilo will give her access to Cardano Indonesia Twitter account
   - Twitter Space: @dionsetyotomo & @CryptoCaliburn, starting regular Twitter Space and/or Telegram Voice during weekdays about Cardano and its ecosystem. This will be started regularly around 17:15 or after 20:00 WIB
- **Discord** -> Status: ***On Hold***
- **Telegram**
   - Ayu, increase engagement in Telegram to increase followers. Regular post at a specific time. @andreassosilo will give her access as admins in the Cardano Indonesia Telegram account

### 3. Community Operation
Proposal Drafts for Catalyst Fund 10:
 1) **Cardano Hub Indonesia - Workshops** -> Status: ***On Hold***
    - Ask to fund for Cardano Hub Indonesia operation
    - @YanTirta & @dionsetyotomo: create Google Sheets for our draft proposal, try to use the Eastern Town Hall Team Operation proposal. [Google Sheet](https://docs.google.com/spreadsheets/d/1yIpVVbFUZHuze5fxZzMfTYQeZRz7auxUX6EMloq8WjY/edit?usp=sharing) 
    - Example proposal from Eastern Town Hall Team Operation: https://docs.google.com/document/d/1lfgePHdJyEW2pDZ8EnL2wCjuJ7wgBQHc/edit?usp=sharing&ouid=116783838297278560675&rtpof=true&sd=true
    - The core team must be compensated -> meeting: 15 USD/hour for example
    - Has dedicated admins
    - @dionsetyotomo will create a matrix
    - Range from admin (30 USD/hour) until developer (100 USD/hour) -> example from other proposal in Catalyst
    - Need more brainstorming
    - Put a maximum cap for the contribution each month
    - Target: support members to become proposers and submit proposals in each Catalyst Fund, collaborate with members from other countries
    - Input from @dionsetyotomo & @YanTirta : for event (max. 3 months), for regular meetup/workshops (max. 6 months)

2) **Community SPO NFT** -> by: @YanTirta - ***TBD***
3) **Cardano Hub UGM** -> by: @danivideda - ***TBD***

### 4. Collaboration
- TRIV
   - Randy contacted @YanTirta -> to create a Cardano event in Surabaya -> budget from TRIV (10 million IDR) -> hybrid event on Saturday, 25 Jun 2022 (18:30 - 20:30) -> will be organized by @YanTirta, @dionsetyotomo, & @CryptoCaliburn 
   - Updates:
      - Budget will be transferred on May 31 2022 to pay mostly for accommodations & transport.
      - Will be further updated by @YanTirta on the google sheet
      - Workshop session
      - Content preparation: CNFT - ***cancelled***
      - Collaboration with Indonesia's Chainlink community
      
### 5. Cardano Summit 2022
- Around August or September 2022
- Community workshop
- What do we want to do for this year -> small gathering in Jakarta?
- Need to ask EMURGO Indonesia if they will create an event for Cardano Summit 2022 by @zicozibu 
- @dionsetyotomo will contact Doddy Emurgo Indonesia
- Another option: to have a self-funded event, need some venue space options: co-working spaces, restaurants with min budget around 100k-150k/person

### a. Cardano Hub Indonesia - Workshops
- @andreassosilo needs to pay the compensation for May 2022 workshops (DELAYED)
- Next workshop:  Sunday, 12 June 2022 at 19:00-21:00 WIB
- Topic: "Introduction to Cardano NFT"
- Speaker: ???
- Host: @andreassosilo 
- Co-Host: @andrecahyadi 
- Reward: 2x 10 ADA + 2x (NFT + 2 ADA) -> need to be send to $cardano_id by @andreassosilo , will be verified by @andrecahyadi 
- Next Workshops' schedule:
1. 12 June 2022: Introduction to Cardano NFT (AMA: how to mint, how to register/validate in the marketplace, royalty CIP-777, how to get profit from buying/selling NFT, discussion about NFT use cases) -> Follow up Omar from Fibo NFT Marketplace by @dionsetyotomo 
2. 26 June 2022: Cardano Ecosystem June 2022
3. 10 July 2022: AMA (with Blue Korintji?) -> Follow up Bayu Isman by @dionsetyotomo  
4. 24 July 2022: Cardano Ecosystem July 2022
5. August/September 2022: "How to setup stake pool in Cardano" by Andrew Ponto

### b. DID for Cardano Indonesia Community
- Learn about (WAL-CLI)[https://github.com/roots-id/wal-cli] -> needs to be read and tested
- Watch [YouTube demo](https://www.youtube.com/watch?v=_9T0JwbNdxU) for WAL-CLI: 
- @danivideda starts helping on research and learning about Atala PRISM, SSI, DID, and VC
- Submitted the monthly KPI report for May 2022 to IOG Catalyst Team (DONE)

### c. Community Web Portal in Bahasa
- Link website: https://www.adakita.xyz/ (**Live**)
- Waiting for article submission
- Compensation -> 10 USD/article becoming 10 ADA/article -> needs to be verified by @dionsetyotomo, @bogelgelbo 
- Submit Article Link: https://docs.google.com/forms/d/e/1FAIpQLSd68yh8gLdurHwePjz_c7wxA1JmqU2KGh6eXkqP1obQeYPOTA/viewform?pli=1
- Fund for May 2022 not yet received -> will be confirmed again later
- Submitted the monthly KPI Report May 2022 to IOG Catalyst Team @dionsetyotomo, @bogelgelbo 
- Closing report to be followed up @dionsetyotomo, @bogelgelbo

**Comment by zicozibu** [comment]
For #5, about the Cardano Summit 2022: Emurgo will hear it from IOG about this, but the date should be in September 2022, the birthday/month of Cardano
