### ISSUE TITLE
Cardano Indonesia Team Meeting #45: 09 until 15 January 2023

### ISSUE THREAD

**Issue by syarbel** [cardano-indonesia/cardano-indonesia-operations#71]
## Cardano Indonesia Meeting: 09 November 2023 until 15 January 2023
- Last Meeting - #70                          
- Next Meeting - TBD 

### Attendees:
Andreas Sosilo (@andreassosilo)
Caliburn (@CryptoCaliburn) 
Fanny Wijaya (@Fny-ETH) 
Gorga Siagian (@gorgagian123)
Yan Tirta (@YanTirta)
Valdryan Ivandito (@ValdryanIvandito)
Xavier Daniswara (@syarbel)

### Apologies:
Andre Cahyadi (@andrecahyadi)
Andy Sibuea (@zicozibu)
Abang Edwin
Dani Ihza Farrosi (@danivideda)
Dion Setyotomo (@dionsetyotomo)
Felix (Pamankripto)
Jordy Vincent (@jordyvincent)
Ivan Kwananda (@ivankwan88)

## Pending Tasks
- @andreassosilo needs to upload all of the remaining Zoom recording + intro + end screen for YouTube to @YanTirta 
- @YanTirta : combine the intro + recording + end screen + upload to YouTube channel "Komunitas Cardano Indonesia"

### 1. Eastern Town Hall Indonesia
- Next meetup: Saturday, 14 January 2023
- Catalyst Fund 10 will start again in 2nd week of January 2023 (TBD) -> waiting for special voting event

### 2. Eastern Catalyst School Indonesia
- Check the list of issue & work for project management in Fund 9 for payment -> @andreassosilo 
- Preparation for 10th workshop (TBA) -> slide will be created by @syarbel 
- Speaker: ???
- ECS Indo doesn't have budget for 1-on-1 session in Fund 10 -> Vietnam & Indonesia will ask Yuta-san from Japan to get some of Japanese Team budget in Fund 9 that is not used -> @YanTirta or @zicozibu will ask Yuta
- **Optional:** host & moderator budget will be allocated for 1-on-1 session if urgently needed -> 720 USD
- Eastern Catalyst School Indonesia Wallet : **$indonesia.ecs** managed by @danivideda @syarbel @zicozibu 
- F10: Eastern Catalyst School -> only Indonesia, South Korea & Vietnam -> proposal will be created by @YanTirta @andreassosilo

### 3. Gimbalabs Indonesia
- In the Fund 10, @YanTirta , @gorgagian123 , @ValdryanIvandito, Sonny & @andreassosilo will create proposal for Gimbalabs Indonesia
- Meeting with James (Gimbalabs) on Thursday, 01 Dec 2022 at 16:00-17:00 UTC (DONE). Discussion about tokenomics & sustainability -> Next step: build proposal -> agree with the KPI -> completion date
- We will receive GMBL tokens + how to support creating dApps under Gimbalabs
- We will support part of the annual fee for the Canvas (14k USD/year)
- Translation all PPBL content, subtitle for video, weekly coding session (12x sessions)
- Gimbalabs will support -> 1 hour open office per week (for Q&A)
- GitHub repo: https://github.com/cardano-indonesia/gimbalabs-indonesia
- @ValdryanIvandito : share documentation for cardano-cli
- @YanTirta had meeting with James Gimbalabs -> will try to get funding from other resources -> waiting for further information
- @ValdryanIvandito @YanTirta @gorgagian123 @andreassosilo : we need separate meeting to discuss about roadmap
- There will be change in PPBL -> will finish in March 2023 -> need to translate the new material

### 4. Catalyst Incubator
- Catalyst Incubator is an effort to structure all Eastern Town Hall programs (Eastern Catalyst School, bi-weekly meetup itself)
- All existing programs will be integrated in Catalyst Incubator. Therefore, there will be minimum additional effort
- Main target is new proposer and those who do not speak/write English properly 
- Business model: referrer goes to Eastern Town Hall. But for direct individual who create the proposal can request "x" number of USD in project management budget
- Status: Corin from Australia will lead this project + participants will be onboarded
- Dani & Mas Sonny Dhamayana applied for this incubator

### 5. Social Engagement
- Collected data ["Cardano Indonesia Social Media Growth"](https://docs.google.com/spreadsheets/d/1suCmuWlZm6jgK67lMWZJP77Fqzb4isye-AO_Zgidri8/edit#gid=1014608380) - created by @dionsetyotomo 
Input by: @andreassosilo 
- **Telegram Cardano Indonesia**
   - Need to do the transition from Shieldy bot to the Rose bot -> maybe we can combined both of them, because we need Shieldy for better spam protection
   - Do regular update for the single [Google Docs](https://docs.google.com/document/d/1ixz4UegskdJxiEIyXMNO90jD6SBIPs02yKkVuu4QHQ4/edit?usp=sharing) for the message for each command that can be updated by every administrator by @andrecahyadi 

### 6. Collaboration
- Cardano Indonesia x Bittime
   - Want to do presentation in our monthly workshop -> 30 mins
   - Initial meeting: Wednesday,  30 November 2022 from 16:00-17:00 WIB via Google Meet @Fny-ETH 
   - Soft launching -> want to list Cardano
   - Try to combine with meetup in Cardano Hub Surabaya -> contact @Fny-ETH @CryptoCaliburn
   - Date: TBD
- KTN (Komunitas Trader Nasional)
   - Ask for AMA on their side @ivankwan88 
   - Cardano Indonesia can share information about Cardano in this AMA
   - Date: TBD (January 2023) 
- Blueshift x Cardano Indonesia
  - They want to present about Blueshift DEX AMM in Komunitas Cardano Indonesia
  - Maybe on Cardano Ecosystem Meetup in January 2023 -> Scheduled: Sunday, 29 January 2023
  - Meeting with @andreassosilo & Wisnu (EMURGO Indonesia) on Friday, 02 December 2022
- Cardano for Women x Cardano Indonesia -> Women in Crypto with Coinvestasi Indonesia
  - Discussion with Niki from Coinvestasi @Fny-ETH 
  - Create event for women in crypto
  - Next meeting with Mbak Dhara (EMURGO Indonesia)

### 7. Cardano Hub Surabaya 
- Meetup Group [Cardano Blockchain Surabaya](https://www.meetup.com/Cardano-Blockchain-Surabaya/)
- Planning **once a month** offline meetup in Bare Coffee, Surabaya
- Next meetup -> February 2023
- In Fund 10, @ivankwan88 & @Fny-ETH (proposer & co-proposer) + supported by Cardano Indonesia. Proposal: "Cardano Hub Surabaya" -> need to discuss regarding the budget breakdown & activities for 3 months -> need revision
- Wallet Cardano Hub Surabaya -> **$cardano.sby** / **$cardanosurabaya**

### 8. Cardano Hub Yogyakarta
- Cardano Hub Yogyakarta -> @YanTirta together with Lutvi Rosyady -> build developer hub using PPBL (plutus project-based learning) system -> topic about gaming -> pending
      
### 9. Cardano Summit 2022 Jakarta
- @andreassosilo @YanTirta : need to have meeting & approve the final video
- Meeting/discussion with the rest of the budget
- Cardano Summit 2023 host application -> Cardano Summit Jakarta -> @syarbel will apply, supported by @andreassosilo @CryptoCaliburn and other Cardano Indonesia Core Team -> will be submitted Sunday, 15 January 2023
- Rendy -> coinstore -> want to increase awareness about Cardano -> try to check if we can do partnership -> Koh Irfan
- Try to find bigger venue (200 people) -> @syarbel @Fny-ETH @CryptoCaliburn @andrecahyadi 

### 10. Cardano Indonesia Community Monthly Digest (December 2022)
- @andreassosilo created monthly digest for December 2022 in Cardano Forum. See [here](https://forum.cardano.org/t/cardano-indonesia-community-monthly-digest-november-2022/111029) -> TBA

#### a. Cardano Hub Indonesia - Workshops
- We are done -> Next step: Yan/Dion needs to edit & upload 17 videos + revision for all meetup recap + clean up GitHub rep + create 3-5 mins report video + 3 pages close-out report
- Close out report will be submitted before 24 Dec 2022
- Cardano Indonesia will be lead by @syarbel @ivankwan88 @Fny-ETH (proposer & co-proposer) -> accounting @Fny-ETH , lead @syarbel & @ivankwan88 , supported by all Cardano Indonesia team member

#### b. DID for Cardano Indonesia Community
- Finished creating schema for booking ticket & check-in Cardano Summit 2022 Jakarta
- Homework: create schema & implementing interaction/service for membership & workshop certificate
- Target: waiting for maintenance/upgrade on Atala PRISM in pre-production testnet in early of November 2022
- Will not received any fund, waiting for the close out report in December 2022
- @andreassosilo submitted the monthly KPI report for October 2022
- Creating workflow for Cardano Indonesia Membership & Workshop Certificate Verifiable Credential (DONE)
- Will implement the simple database in the integration for check-in, as ProofSpace doesn't have "revoking" feature yet
- Close out report Dec 2022

#### c. AMA with Cross-Chain Communities
- 3rd AMA: Sunday, 15 January 2023: AMA Cross-Chain with NEAR protocol (Dery)
- From Cardano Indonesia, @andreassosilo will represent Komunitas Cardano Indonesia
- [Meetup event link for 3rd AMA](https://www.meetup.com/cardano-blockchain-jakarta/events/289641452/)
- Flyer (DONE) -> inform to the communities (DONE)

**Comment by andreassosilo** [comment]
Done. Closed.
